---
name: Run tests
on:
  pull_request: ~
  push:
    branches:
      - master

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        neovim_version: ['nightly', 'v0.10.0']

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Install neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.neovim_version }}

      - name: Install treesitter
        uses: tree-sitter/setup-action@v1
        with:
          install-lib: false

      - name: Install Lua
        uses: leso-kn/gh-actions-lua@master
        with:
          luaVersion: "5.1"

      - name: Install Luarocks
        uses: hishamhm/gh-actions-luarocks@master
        with:
          luarocksVersion: "3.11.0"

      - name: Install tree-sitter-python
        run: |
          luarocks install tree-sitter-python --local

      - name: Copy python.so
        run: |
          mkdir -p ~/.config/nvim/parser
          find ~/.luarocks -name python.so -exec cp {} ~/.config/nvim/parser/python.so \;

      - name: Run tests
        run: |
          luarocks test --local
